use demo_microservice;
insert into product (name, price, category) values ('Tuna - Canned, Flaked, Light', '689000', 'CAT09TEST');
insert into product (name, price, category) values ('Wanton Wrap', '676000', 'CAT16TEST');
insert into product (name, price, category) values ('Mix - Cocktail Strawberry Daiquiri', '1927000', 'CAT21TEST');
insert into product (name, price, category) values ('Beer - True North Lager', '4519000', 'CAT15TEST');
insert into product (name, price, category) values ('Beef - Tenderloin Tails', '41746000', 'CAT21TEST');
insert into product (name, price, category) values ('Turkey - Oven Roast Breast', '7000', 'CAT28TEST');
insert into product (name, price, category) values ('Wine - Ej Gallo Sonoma', '53000', 'CAT05TEST');
insert into product (name, price, category) values ('Wine - Red, Concha Y Toro', '788712000', 'CAT18TEST');
insert into product (name, price, category) values ('Marjoram - Fresh', '817000', 'CAT26TEST');
insert into product (name, price, category) values ('Isomalt', '2000', 'CAT20TEST');
insert into product (name, price, category) values ('Towel Multifold', '1000', 'CAT22TEST');
insert into product (name, price, category) values ('Plums - Red', '735000', 'CAT06TEST');
insert into product (name, price, category) values ('Beer - Moosehead', '162000', 'CAT20TEST');
insert into product (name, price, category) values ('Dc Hikiage Hira Huba', '7000', 'CAT18TEST');
insert into product (name, price, category) values ('Beer - Paulaner Hefeweisse', '73264000', 'CAT27TEST');
insert into product (name, price, category) values ('Foam Espresso Cup Plain White', '57452000', 'CAT25TEST');
insert into product (name, price, category) values ('Wasabi Powder', '47679000', 'CAT13TEST');
insert into product (name, price, category) values ('Bandage - Finger Cots', '540029000', 'CAT27TEST');
insert into product (name, price, category) values ('Bay Leaf', '090000', 'CAT27TEST');
insert into product (name, price, category) values ('Compound - Mocha', '312125000', 'CAT28TEST');
insert into product (name, price, category) values ('Beans - Turtle, Black, Dry', '28840000', 'CAT16TEST');
insert into product (name, price, category) values ('Extract - Vanilla,artificial', '2000', 'CAT24TEST');
insert into product (name, price, category) values ('Soup Campbells - Italian Wedding', '0710000', 'CAT29TEST');
insert into product (name, price, category) values ('Pepper - Pablano', '2389000', 'CAT25TEST');
insert into product (name, price, category) values ('Instant Coffee', '702138000', 'CAT20TEST');
insert into product (name, price, category) values ('Sea Bass - Fillets', '531065000', 'CAT15TEST');
insert into product (name, price, category) values ('Scampi Tail', '27801000', 'CAT02TEST');
insert into product (name, price, category) values ('Beans - French', '4000', 'CAT13TEST');
insert into product (name, price, category) values ('Pork - Bacon Cooked Slcd', '5289000', 'CAT18TEST');
insert into product (name, price, category) values ('Mushroom - Porcini Frozen', '6893000', 'CAT11TEST');
insert into product (name, price, category) values ('External Supplier', '1534000', 'CAT25TEST');
insert into product (name, price, category) values ('Crackers - Water', '066000', 'CAT27TEST');
insert into product (name, price, category) values ('Cranberries - Frozen', '2000', 'CAT20TEST');
insert into product (name, price, category) values ('Sping Loaded Cup Dispenser', '7000', 'CAT28TEST');
insert into product (name, price, category) values ('Chips - Potato Jalapeno', '5000', 'CAT12TEST');
insert into product (name, price, category) values ('Wine - Wyndham Estate Bin 777', '9077000', 'CAT03TEST');
insert into product (name, price, category) values ('Soup V8 Roasted Red Pepper', '88000', 'CAT16TEST');
insert into product (name, price, category) values ('Chinese Lemon Pork', '84262000', 'CAT27TEST');
insert into product (name, price, category) values ('Longan', '3994000', 'CAT23TEST');
insert into product (name, price, category) values ('Flour - Pastry', '1959000', 'CAT03TEST');
insert into product (name, price, category) values ('Wine - Alsace Riesling Reserve', '483000', 'CAT24TEST');
insert into product (name, price, category) values ('Beer - Upper Canada Light', '8651000', 'CAT05TEST');
insert into product (name, price, category) values ('Potatoes - Idaho 100 Count', '111951000', 'CAT23TEST');
insert into product (name, price, category) values ('Stock - Beef, Brown', '58000', 'CAT22TEST');
insert into product (name, price, category) values ('Eggwhite Frozen', '098000', 'CAT18TEST');
insert into product (name, price, category) values ('Beer - Molson Excel', '78000', 'CAT14TEST');
insert into product (name, price, category) values ('Red Currants', '79000', 'CAT10TEST');
insert into product (name, price, category) values ('Wine - Prosecco Valdobienne', '199330000', 'CAT02TEST');
insert into product (name, price, category) values ('Jagermeister', '1000', 'CAT26TEST');
insert into product (name, price, category) values ('Tomato - Plum With Basil', '5000', 'CAT06TEST');
insert into product (name, price, category) values ('Sultanas', '34000', 'CAT20TEST');
insert into product (name, price, category) values ('Onions Granulated', '3042000', 'CAT28TEST');
insert into product (name, price, category) values ('Sprouts - China Rose', '4000', 'CAT13TEST');
insert into product (name, price, category) values ('French Kiss Vanilla', '978638000', 'CAT03TEST');
insert into product (name, price, category) values ('Guinea Fowl', '228794000', 'CAT27TEST');
insert into product (name, price, category) values ('Versatainer Nc - 888', '78000', 'CAT03TEST');
insert into product (name, price, category) values ('Pepper - Chili Powder', '876000', 'CAT24TEST');
insert into product (name, price, category) values ('Nut - Pecan, Halves', '3284000', 'CAT01TEST');
insert into product (name, price, category) values ('Ecolab - Solid Fusion', '285232000', 'CAT29TEST');
insert into product (name, price, category) values ('Sausage - Andouille', '31473000', 'CAT17TEST');
insert into product (name, price, category) values ('Chambord Royal', '4581000', 'CAT16TEST');
insert into product (name, price, category) values ('Corn - On The Cob', '1862000', 'CAT08TEST');
insert into product (name, price, category) values ('Pork Casing', '950958000', 'CAT02TEST');
insert into product (name, price, category) values ('Artichoke - Hearts, Canned', '88000', 'CAT28TEST');
insert into product (name, price, category) values ('Chocolate - Liqueur Cups With Foil', '8000', 'CAT24TEST');
insert into product (name, price, category) values ('Shiratamako - Rice Flour', '91000', 'CAT03TEST');
insert into product (name, price, category) values ('Coffee - Cafe Moreno', '67764000', 'CAT00TEST');
insert into product (name, price, category) values ('Salmon - Whole, 4 - 6 Pounds', '9000', 'CAT23TEST');
insert into product (name, price, category) values ('Sansho Powder', '2465000', 'CAT22TEST');
insert into product (name, price, category) values ('Coffee - Ristretto Coffee Capsule', '9000', 'CAT25TEST');
insert into product (name, price, category) values ('Doilies - 5, Paper', '1000', 'CAT08TEST');
insert into product (name, price, category) values ('Pastry - Banana Muffin - Mini', '62000', 'CAT23TEST');
insert into product (name, price, category) values ('Bamboo Shoots - Sliced', '1000', 'CAT16TEST');
insert into product (name, price, category) values ('Mushroom - Morel Frozen', '1245000', 'CAT27TEST');
insert into product (name, price, category) values ('Pork - Liver', '1786000', 'CAT16TEST');
insert into product (name, price, category) values ('Table Cloth 90x90 Colour', '64554000', 'CAT12TEST');
insert into product (name, price, category) values ('Cheese - Swiss Sliced', '53418000', 'CAT22TEST');
insert into product (name, price, category) values ('Squid - Tubes / Tenticles 10/20', '5000', 'CAT26TEST');
insert into product (name, price, category) values ('Puree - Guava', '9614000', 'CAT13TEST');
insert into product (name, price, category) values ('Cheese - Taleggio D.o.p.', '352118000', 'CAT28TEST');
insert into product (name, price, category) values ('Wine - Pinot Noir Stoneleigh', '39000', 'CAT23TEST');
insert into product (name, price, category) values ('Cucumber - English', '025000', 'CAT07TEST');
insert into product (name, price, category) values ('Cup - 3.5oz, Foam', '51513000', 'CAT23TEST');
insert into product (name, price, category) values ('Oil - Coconut', '7519000', 'CAT21TEST');
insert into product (name, price, category) values ('Pork - Loin, Bone - In', '2370000', 'CAT25TEST');
insert into product (name, price, category) values ('Tomato - Peeled Italian Canned', '693000', 'CAT19TEST');
insert into product (name, price, category) values ('Liquid Aminios Acid - Braggs', '12789000', 'CAT24TEST');
insert into product (name, price, category) values ('Bread - Dark Rye, Loaf', '135873000', 'CAT05TEST');
insert into product (name, price, category) values ('Wine - Mas Chicet Rose, Vintage', '448236000', 'CAT18TEST');
insert into product (name, price, category) values ('Soup - Campbells - Chicken Noodle', '23000', 'CAT22TEST');
insert into product (name, price, category) values ('Zucchini - Green', '9235000', 'CAT24TEST');
insert into product (name, price, category) values ('Coffee Cup 8oz 5338cd', '62965000', 'CAT29TEST');
insert into product (name, price, category) values ('Easy Off Oven Cleaner', '0000', 'CAT28TEST');
insert into product (name, price, category) values ('Whmis - Spray Bottle Trigger', '9992000', 'CAT18TEST');
insert into product (name, price, category) values ('Cocoa Feuilletine', '679000', 'CAT10TEST');
insert into product (name, price, category) values ('Brandy - Bar', '9934000', 'CAT17TEST');
insert into product (name, price, category) values ('Crawfish', '33000', 'CAT17TEST');
insert into product (name, price, category) values ('Tea - Darjeeling, Azzura', '755682000', 'CAT28TEST');
insert into product (name, price, category) values ('Persimmons', '232810000', 'CAT24TEST');
insert into product (name, price, category) values ('Quinoa', '660137000', 'CAT22TEST');
